# Generated by Django 4.2.1 on 2023-06-03 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0002_alter_post_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_użytkownika', models.CharField(max_length=128)),
                ('haslo', models.CharField(max_length=128)),
                ('imie', models.CharField(max_length=128)),
                ('nazwisko', models.CharField(max_length=128)),
                ('miejsce_zamieszkania', models.CharField(max_length=128)),
                ('opis', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 14, 20, 13, 553838, tzinfo=datetime.timezone.utc)),
        ),
    ]
