# Generated by Django 4.2.1 on 2023-06-03 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_profil_alter_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='nazwa_użytkownika',
            new_name='nazwa_uzytkownika',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 14, 21, 7, 551641, tzinfo=datetime.timezone.utc)),
        ),
    ]
