# Generated by Django 4.2.1 on 2023-06-03 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0004_rename_nazwa_użytkownika_profil_nazwa_uzytkownika_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 14, 22, 32, 445792, tzinfo=datetime.timezone.utc)),
        ),
    ]
