# Generated by Django 4.2.1 on 2023-06-03 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0005_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 15, 5, 47, 344251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profil',
            name='opis',
            field=models.TextField(),
        ),
    ]
