# Generated by Django 4.2.1 on 2023-06-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0022_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 16, 1, 9, 751516, tzinfo=datetime.timezone.utc)),
        ),
    ]
