# Generated by Django 4.2.1 on 2023-06-12 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0023_alter_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 12, 28, 6, 866314, tzinfo=datetime.timezone.utc)),
        ),
    ]
