# Generated by Django 4.2.1 on 2023-06-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0026_remove_profil_haslo_remove_profil_imie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 17, 3, 29, 862132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
