# Generated by Django 4.2.1 on 2023-06-15 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0028_alter_post_published_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 17, 13, 4, 160241, tzinfo=datetime.timezone.utc)),
        ),
    ]
