# Generated by Django 4.2.1 on 2023-06-16 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0031_profile_alter_post_published_delete_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 18, 40, 14, 831158, tzinfo=datetime.timezone.utc)),
        ),
    ]
