# Generated by Django 4.2.1 on 2023-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwierkacz', '0002_profil_remove_movie_genre_delete_genre_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
