# Generated by Django 4.2.1 on 2023-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwierkacz', '0003_profil_opis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='login',
            new_name='nazwa_użytkownika',
        ),
    ]
