# Generated by Django 4.2.1 on 2023-06-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwierkacz', '0004_rename_login_profil_nazwa_użytkownika'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
